<a href="https://colab.research.google.com/github/ThaisEDomingues/genCripto/blob/main/Preco_mercado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import yfinance as yf
import pandas as pd
import os

# Dicionário com o nome da empresa e o ticker (código do ativo no Yahoo Finance)
ativos = {
    'Google': 'GOOGL',
    'Amazon': 'AMZN',
    'Microsoft': 'MSFT',
    'Bitcoin': 'BTC-USD',
    'Mercado Livre': 'MELI'
}

# Criar uma pasta para salvar os arquivos
os.makedirs('dados_ativos', exist_ok=True)

for nome, ticker in ativos.items():
    # Baixando o histórico do último ano
    df = yf.download(ticker, period="1y")

    # Resetando o index para transformar a Data em coluna
    df = df.reset_index()

    # Criando a coluna com o Código do Ativo para facilitar no Power BI
    df['Codigo_Ativo'] = ticker

    # Selecionando apenas as colunas relevantes (Data, Fechamento, etc)
    df = df[['Date', 'Close', 'Codigo_Ativo']]
    df.columns = ['Data', 'Preco_Fechamento', 'Codigo_Ativo'] # Renomeando

    # Exportando para CSV
    nome_arquivo = f"dados_ativos/{ticker}_historico.csv"
    df.to_csv(nome_arquivo, index=False)

print("Arquivos CSV gerados com sucesso na pasta 'dados_ativos'!")

/tmp/ipykernel_6185/4143735335.py:19: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="1y")
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_6185/4143735335.py:19: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="1y")
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_6185/4143735335.py:19: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="1y")
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_6185/4143735335.py:19: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="1y")
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_6185/4143735335.py:19: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="1y")
[*********************100%***********************]  1 of 1 completed

Arquivos CSV gerados com sucesso na pasta 'dados_ativos'!

In [2]:

#criar variavel para receber os dados das tabela. Essas variaveis vão receber o resultado
# da funcao do pandas que le um arquivo .csv

#as variaveis vendas_janeiro, vendas_fevereiro e vendas_marco ...
#estão recebendo o conteudo dos arquvivos .csv que estão sendo lidos pela função read da biblioteca pandas


amzn = pd.read_csv('/content/dados_ativos/AMZN_historico.csv')
btc = pd.read_csv('/content/dados_ativos/BTC-USD_historico.csv')
googl = pd.read_csv('/content/dados_ativos/GOOGL_historico.csv')
meli = pd.read_csv('/content/dados_ativos/MELI_historico.csv')
msft = pd.read_csv('/content/dados_ativos/MSFT_historico.csv')

In [5]:

#para transformar os dados destres arquivos .csv em dataframe usando esse função da biblioteca panda
# ex df_dados = pd.DataFrame(dados)



df_amzn = pd.DataFrame(amzn)
df_btc = pd.DataFrame(btc)
df_googl = pd.DataFrame(googl)
df_meli = pd.DataFrame(meli)
df_msft = pd.DataFrame(msft)

           Data  Preco_Fechamento Codigo_Ativo
0    2025-05-23        200.990005         AMZN
1    2025-05-27        206.020004         AMZN
2    2025-05-28        204.720001         AMZN
3    2025-05-29        205.699997         AMZN
4    2025-05-30        205.009995         AMZN
..          ...               ...          ...
246  2026-05-18        264.859985         AMZN
247  2026-05-19        259.339996         AMZN
248  2026-05-20        265.010010         AMZN
249  2026-05-21        268.459991         AMZN
250  2026-05-22        266.320007         AMZN

[251 rows x 3 columns]

In [6]:
#usa a funcao pd.concat para juntar os dados de tabelas diferentes
# pd.concat([dados_antigos, dados_novos], ignore_index=True)

df_preco_mercado = pd.concat([df_amzn,df_btc,df_googl,df_meli,df_msft], ignore_index=True)

display(df_preco_mercado)

            Data  Preco_Fechamento Codigo_Ativo
0     2025-05-23        200.990005         AMZN
1     2025-05-27        206.020004         AMZN
2     2025-05-28        204.720001         AMZN
3     2025-05-29        205.699997         AMZN
4     2025-05-30        205.009995         AMZN
...          ...               ...          ...
1365  2026-05-18        422.624664         MSFT
1366  2026-05-19        416.517883         MSFT
1367  2026-05-20        420.149994         MSFT
1368  2026-05-21        419.089996         MSFT
1369  2026-05-22        418.570007         MSFT

[1370 rows x 3 columns]

In [7]:
#para exportar o arquivo .csv para seu pc
df_preco_mercado.to_csv("Preço_mercado.csv", index=False)